apiVersion: apps/v1
kind: Deployment
metadata:
  name: dish-lab-mongo
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dish-lab-mongo
  template:
    metadata:
      labels:
        app: dish-lab-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: dish-lab-mongo-secret
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: dish-lab-mongo-data
