apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proto-pump-postgres-data
  namespace: data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
